"""
Data types for AI-enhanced semantic chunking.

This module defines data structures used by the semantic chunking system
for AI-generated metadata and document structure analysis.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


@dataclass
class ChunkMetadata:
    """
    AI-generated metadata for a document chunk.
    
    This dataclass stores metadata generated by AI analysis of chunk content,
    including summaries, keywords, and topic information. Used by the
    MetadataGenerator component before assigning to DocumentChunk instances.
    
    Attributes:
        summary: Concise summary of chunk content (max 150 characters)
        keywords: List of 3-7 keywords extracted from the chunk
        topic: Primary topic of the chunk
        structure_type: Type of structure in chunk (e.g., "list", "table", "paragraph")
        heading_context: Relevant heading that provides context for this chunk
    
    Raises:
        ValueError: If summary exceeds 150 characters or keywords count is not 3-7
    """
    summary: str
    keywords: List[str]
    topic: str
    structure_type: Optional[str] = None
    heading_context: Optional[str] = None
    
    def __post_init__(self):
        """
        Validate metadata fields after initialization.
        
        Ensures:
        - Summary does not exceed 150 characters
        - Keywords list contains between 3 and 7 items
        
        Raises:
            ValueError: If validation fails with clear error message
        """
        self.validate()
    
    def validate(self) -> None:
        """
        Validate summary length and keywords count.
        
        Raises:
            ValueError: If summary exceeds 150 characters
            ValueError: If keywords count is not between 3 and 7
        """
        # Validate summary length
        if len(self.summary) > 150:
            raise ValueError(
                f"Summary exceeds maximum length of 150 characters "
                f"(got {len(self.summary)} characters)"
            )
        
        # Validate keywords count
        if not (3 <= len(self.keywords) <= 7):
            raise ValueError(
                f"Keywords must contain between 3 and 7 items "
                f"(got {len(self.keywords)} keywords)"
            )


@dataclass
class HeadingNode:
    """
    Represents a heading in the document hierarchy.
    
    Attributes:
        position: Character offset of the heading in the document
        level: Heading level (1-6)
        text: Heading text content
        start_pos: Start position of content under this heading
        end_pos: End position of content under this heading (exclusive)
        parent: Parent heading node (None for top-level headings)
        children: List of child heading nodes
    """
    position: int
    level: int
    text: str
    start_pos: int
    end_pos: int
    parent: Optional['HeadingNode'] = None
    children: List['HeadingNode'] = field(default_factory=list)
    
    def get_full_path(self) -> List[str]:
        """
        Get the full heading path from root to this heading.
        
        Returns:
            List of heading texts from root to current heading
            
        Example:
            >>> node.get_full_path()
            ['Introduction', 'Background', 'History']
        """
        path = []
        current = self
        while current is not None:
            path.insert(0, current.text)
            current = current.parent
        return path


@dataclass
class StructureInfo:
    """
    Document structure analysis results.
    
    This dataclass stores the results of document structure analysis performed
    by the StructureAnalyzer component. It identifies and tracks structural
    elements like headings, lists, tables, and code blocks within documents.
    
    Used to preserve document structure during semantic chunking, ensuring that
    structural elements remain intact and contextual information is maintained.
    
    Attributes:
        headings: List of heading information as (position, level, text) tuples
                 where position is character offset, level is 1-6 (# to ######),
                 and text is the heading content
        lists: List of list positions as (start_pos, end_pos) tuples for both
              ordered and unordered lists
        tables: List of table positions as (start_pos, end_pos) tuples
        code_blocks: List of code block positions as (start_pos, end_pos) tuples
        heading_hierarchy: Dictionary mapping character positions to (level, text)
                          tuples for quick heading context lookup (legacy)
        heading_tree: List of root-level HeadingNode objects representing the
                     document's heading hierarchy with parent-child relationships
        position_to_heading: Dictionary mapping any position in the document to
                            the HeadingNode that contains it
    
    Example:
        >>> structure = StructureInfo(
        ...     headings=[(0, 1, "Introduction"), (100, 2, "Background")],
        ...     lists=[(50, 80)],
        ...     tables=[(200, 300)],
        ...     code_blocks=[(400, 500)],
        ...     heading_hierarchy={0: (1, "Introduction"), 100: (2, "Background")}
        ... )
    """
    headings: List[Tuple[int, int, str]] = field(default_factory=list)
    lists: List[Tuple[int, int]] = field(default_factory=list)
    tables: List[Tuple[int, int]] = field(default_factory=list)
    code_blocks: List[Tuple[int, int]] = field(default_factory=list)
    heading_hierarchy: Dict[int, Tuple[int, str]] = field(default_factory=dict)
    heading_tree: List[HeadingNode] = field(default_factory=list)
    position_to_heading: Dict[int, HeadingNode] = field(default_factory=dict)
    
    def get_heading_at_position(self, position: int) -> Optional[HeadingNode]:
        """
        Get the heading that contains the given position.
        
        Args:
            position: Character position in the document
            
        Returns:
            HeadingNode containing this position, or None if not under any heading
            
        Example:
            >>> heading = structure.get_heading_at_position(150)
            >>> heading.text
            'Background'
        """
        # Find the deepest heading that contains this position
        for heading_pos in sorted(self.position_to_heading.keys(), reverse=True):
            if heading_pos <= position:
                node = self.position_to_heading[heading_pos]
                if node.start_pos <= position < node.end_pos:
                    return node
        return None
    
    def get_heading_context(self, position: int) -> Optional[str]:
        """
        Get the full heading context path for a given position.
        
        Args:
            position: Character position in the document
            
        Returns:
            Full heading path as a string (e.g., "Introduction > Background > History")
            or None if not under any heading
            
        Example:
            >>> structure.get_heading_context(150)
            'Introduction > Background'
        """
        node = self.get_heading_at_position(position)
        if node is None:
            return None
        return " > ".join(node.get_full_path())
