"""
Motor Screening Skill Configuration

Early movement/gait screening for 3–9 y/o (adult-facing, non-diagnostic).
"""

from .base_skill import SkillConfig
from src.core.prompt_loader import load_skill_prompt

MOTOR_SCREENING_SKILL = SkillConfig(
    name="motor_screening",
    display_name="Motor Development Screening",
    description="Helps adults describe a child's gait/movement and suggest safe next steps (non-diagnostic).",
    keywords_en=[
        "walk",
        "walking",
        "run",
        "running",
        "gait",
        "balance",
        "clumsy",
        "clumsiness",
        "toe walk",
        "toe-walk",
        "toe walking",
        "stumble",
        "trip",
        "coordination",
        "movement",
        "motor",
        "posture",
        "stand",
        "jump",
        "hop",
        "uneven",
        "limp",
        "drag",
        "stiff",
        "screening",
        "check",
        "video",
        "3 year",
        "4 year",
        "5 year",
        "6 year",
        "7 year",
        "8 year",
        "9 year",
        "kindergarten",
        "k2",
        "k3",
        "p1",
        "p2",
        "p3",
    ],
    keywords_zh=[
        "行路",
        "跑步",
        "步姿",
        "平衡",
        "跛",
        "腳尖行",
        "拖腳",
        "跌倒",
        "跌親",
        "跌低",
        "笨手笨腳",
        "幼稚園",
        "小學",
    ],
    priority=70,
    system_prompt_addition=load_skill_prompt("motor_screening", "system_prompt"),
    response_guidelines=load_skill_prompt("motor_screening", "response_guidelines"),
    available_functions=[],
    knowledge_categories=["motor_development", "child_wellbeing"],
    emotion_hints={"concern": "calm"},
    requires_safety_check=True,
)
